#!/usr/bin/perl

# dorpm
# John Jacobsen, NPX Designs, Inc., jacobsen\@npxdesigns.com
# Started: Tue Jul 12 23:00:28 2005

# Procedure:
# update release notes
# tag project with desired <tag>
# "make rpm" invokes dorpm <tag>

use strict;

my $project = "domapp-tools";

print "Welcome to $0.\n";

my $version = shift; chomp $version;
sub usage;
die usage unless defined $version;
print "Version is $version.\n";
my $rpmver = $version; 
$rpmver =~ s/^V//; 
$rpmver =~ s/\-/\./g;
my $verproj = "$project"."-$rpmver";
print "RPM version is $rpmver.\n";

chdir ".." or die "Can't CD .. : $!\n";

# RPM build area
my $RPM_ROOT = "$ENV{HOME}/rpmbuild";

my $r;
$r = `rm -rf $verproj 2>&1`; die "$r\n" unless $r eq "";
$r = `cp -Rp $project $verproj 2>&1`; die "$r\n" unless $r eq "";
$r = `tar czf /tmp/$verproj.tgz --exclude=$verproj/CVS $verproj 2>&1`;
die "$r\n" unless $r eq "";
$r = `cp /tmp/$verproj.tgz ${RPM_ROOT}/SOURCES 2>&1`; die "$r\n" unless $r eq "";
$r = `cp $verproj/$project.spec ${RPM_ROOT}/SPECS/$verproj.spec 2>&1`; 
die "$r\n" unless $r eq "";
chdir "${RPM_ROOT}" or die "Can't CD to ${RPM_ROOT}: $!\n";
system "rpmbuild -ba -D 'VER $rpmver' -D 'REL 0' SPECS/$verproj.spec 2>&1";
print $r;
$r = `rm -rf $verproj 2>&1`; die "$r\n" unless $r eq "";

exit;

sub usage { 
    return <<EOF;
Usage: $0 <version>
EOF
;
}
__END__

